experiment_name: "svhn_mnist_beta_0.1"

general:
  seed: 64

data:
  path: '/home/vcourrier/exploration-encoder-decoder-vae/gcvae/data/data_mnist_svhn'
  batch_size: 500
  shuffle: True

model:
  latent_dim: 20
  hidden_dim: [256]
  n_clusters: 10

pretraining:
  epochs: 5
  lr: 0.0001
  beta: 0.1

training:
  epochs: 100
  lr_nn: 0.0005
  lr_gmm: 0.0005
  beta: 0.1